version: '3.8'

services:
  catalogservice:
    image: chilinhm/catalogservicetest-image
    ports:
      - "5025:8080"
    environment:
      - ConnectionURI=mongodb+srv://admin:admin@auctionhouse.dfo2bcd.mongodb.net/
      - DatabaseName=Catalog
      - CatalogCollectionName=Catalog
      - loki=http://loki:3100
    networks:
      - my_network
    # Konfigurér logning til standardudgangen (stdout)
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    # Angiv Loki URL som miljøvariabel


  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - my_network
    depends_on:
      - loki

  promtail:
    image: grafana/promtail:2.9.4
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - my_network
    depends_on:
      - loki

  loki:
    image: grafana/loki:latest
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
