version: "3.8"

services:
  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - my_network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - my_network

  catalogservicetest:
    image: chilinhm/catalogservicetest-image:latest
    ports:
      - "5125:8080"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge